# Generated by Django 5.1.3 on 2024-11-15 21:32

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin_Level_0",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gid_0",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, default=None, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "ordering": ["gid_0"],
            },
        ),
        migrations.CreateModel(
            name="Timezone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tzid", models.CharField(max_length=80)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="United_States_Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_number",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "street_name",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "street_suffix",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "city_name",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "default_city_name",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "state_abbreviation",
                    models.CharField(blank=True, default=None, max_length=2, null=True),
                ),
                (
                    "zip5",
                    models.CharField(blank=True, default=None, max_length=5, null=True),
                ),
                (
                    "delivery_point",
                    models.CharField(
                        blank=True, default=None, max_length=99, null=True
                    ),
                ),
                (
                    "delivery_point_check_digit",
                    models.CharField(
                        blank=True, default=None, max_length=99, null=True
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "zip_type",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "county_fips",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "county_name",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "carrier_route",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "congressional_district",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "rdi",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "elot_sequence",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "elot_sort",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=16,
                        default=None,
                        max_digits=22,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=16,
                        default=None,
                        max_digits=22,
                        null=True,
                    ),
                ),
                (
                    "coordinate_license",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "precision",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "time_zone",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "utc_offset",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, default=None, null=True, srid=4326
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="United_States_Census_Block_Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statefp", models.CharField(max_length=2)),
                ("countyfp", models.CharField(max_length=3)),
                ("tractce", models.CharField(max_length=6)),
                ("blkgrpce", models.CharField(max_length=1)),
                ("geoid", models.CharField(max_length=12)),
                ("geoidfq", models.CharField(max_length=21)),
                ("namelsad", models.CharField(max_length=13)),
                ("mtfcc", models.CharField(max_length=5)),
                ("funcstat", models.CharField(max_length=1)),
                ("aland", models.BigIntegerField()),
                ("awater", models.BigIntegerField()),
                ("intptlat", models.CharField(max_length=11)),
                ("intptlon", models.CharField(max_length=12)),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=4269)),
                ("year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="United_States_Census_Congressional_District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statefp", models.CharField(max_length=2)),
                ("cd118fp", models.CharField(max_length=2)),
                ("geoid", models.CharField(max_length=4)),
                ("geoidfq", models.CharField(max_length=13)),
                ("namelsad", models.CharField(max_length=41)),
                ("lsad", models.CharField(max_length=2)),
                ("cdsessn", models.CharField(max_length=3)),
                ("mtfcc", models.CharField(max_length=5)),
                ("funcstat", models.CharField(max_length=1)),
                ("aland", models.BigIntegerField()),
                ("awater", models.BigIntegerField()),
                ("intptlat", models.CharField(max_length=11)),
                ("intptlon", models.CharField(max_length=12)),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=4269)),
                ("year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="United_States_Census_County",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statefp", models.CharField(max_length=2)),
                ("countyfp", models.CharField(max_length=3)),
                ("countyns", models.CharField(max_length=8)),
                ("geoid", models.CharField(max_length=5)),
                ("geoidfq", models.CharField(max_length=14)),
                ("name", models.CharField(max_length=100)),
                ("namelsad", models.CharField(max_length=100)),
                ("lsad", models.CharField(max_length=2)),
                ("classfp", models.CharField(max_length=2)),
                ("mtfcc", models.CharField(max_length=5)),
                ("csafp", models.CharField(max_length=3)),
                ("cbsafp", models.CharField(max_length=5)),
                ("metdivfp", models.CharField(max_length=5)),
                ("funcstat", models.CharField(max_length=1)),
                ("aland", models.BigIntegerField()),
                ("awater", models.BigIntegerField()),
                ("intptlat", models.CharField(max_length=11)),
                ("intptlon", models.CharField(max_length=12)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4269),
                ),
                ("year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="United_States_Census_State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=2)),
                ("division", models.CharField(max_length=2)),
                ("statefp", models.CharField(max_length=2)),
                ("statens", models.CharField(max_length=8)),
                ("geoid", models.CharField(max_length=2)),
                ("geoidfq", models.CharField(max_length=11)),
                ("stusps", models.CharField(max_length=2)),
                ("name", models.CharField(max_length=100)),
                ("lsad", models.CharField(max_length=2)),
                ("mtfcc", models.CharField(max_length=5)),
                ("funcstat", models.CharField(max_length=1)),
                ("aland", models.BigIntegerField()),
                ("awater", models.BigIntegerField()),
                ("intptlat", models.CharField(max_length=11)),
                ("intptlon", models.CharField(max_length=12)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4269),
                ),
                ("year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="United_States_Census_State_Legislative_District_Lower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statefp", models.CharField(max_length=2)),
                ("sldlst", models.CharField(max_length=3)),
                ("geoid", models.CharField(max_length=5)),
                ("geoidfq", models.CharField(max_length=14)),
                ("namelsad", models.CharField(max_length=100)),
                ("lsad", models.CharField(max_length=2)),
                ("lsy", models.CharField(max_length=4)),
                ("mtfcc", models.CharField(max_length=5)),
                ("funcstat", models.CharField(max_length=1)),
                ("aland", models.BigIntegerField()),
                ("awater", models.BigIntegerField()),
                ("intptlat", models.CharField(max_length=11)),
                ("intptlon", models.CharField(max_length=12)),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=4269)),
                ("year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="United_States_Census_State_Legislative_District_Upper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statefp", models.CharField(max_length=2)),
                ("sldust", models.CharField(max_length=3)),
                ("geoid", models.CharField(max_length=5)),
                ("geoidfq", models.CharField(max_length=14)),
                ("namelsad", models.CharField(max_length=100)),
                ("lsad", models.CharField(max_length=2)),
                ("lsy", models.CharField(max_length=4)),
                ("mtfcc", models.CharField(max_length=5)),
                ("funcstat", models.CharField(max_length=1)),
                ("aland", models.BigIntegerField()),
                ("awater", models.BigIntegerField()),
                ("intptlat", models.CharField(max_length=11)),
                ("intptlon", models.CharField(max_length=12)),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=4269)),
                ("year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="United_States_Census_Tabulation_Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statefp20", models.CharField(max_length=2)),
                ("countyfp20", models.CharField(max_length=3)),
                ("tractce20", models.CharField(max_length=6)),
                ("blockce20", models.CharField(max_length=4)),
                ("geoid20", models.CharField(max_length=15)),
                ("geoidfq20", models.CharField(max_length=24)),
                ("name20", models.CharField(max_length=10)),
                ("mtfcc20", models.CharField(max_length=5)),
                ("ur20", models.CharField(max_length=1)),
                ("uace20", models.CharField(max_length=5)),
                ("funcstat20", models.CharField(max_length=1)),
                ("aland20", models.BigIntegerField()),
                ("awater20", models.BigIntegerField()),
                ("intptlat20", models.CharField(max_length=11)),
                ("intptlon20", models.CharField(max_length=12)),
                ("housing20", models.BigIntegerField()),
                ("pop20", models.BigIntegerField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4269),
                ),
                ("year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="United_States_Census_Tract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statefp", models.CharField(max_length=2)),
                ("countyfp", models.CharField(max_length=3)),
                ("tractce", models.CharField(max_length=6)),
                ("geoid", models.CharField(max_length=11)),
                ("geoidfq", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=7)),
                ("namelsad", models.CharField(max_length=20)),
                ("mtfcc", models.CharField(max_length=5)),
                ("funcstat", models.CharField(max_length=1)),
                ("aland", models.BigIntegerField()),
                ("awater", models.BigIntegerField()),
                ("intptlat", models.CharField(max_length=11)),
                ("intptlon", models.CharField(max_length=12)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4269),
                ),
                ("year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="United_States_Census_Tribal_Tract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=2)),
                ("division", models.CharField(max_length=2)),
                ("statefp", models.CharField(max_length=2)),
                ("statens", models.CharField(max_length=8)),
                ("geoid", models.CharField(max_length=2)),
                ("geoidfq", models.CharField(max_length=11)),
                ("stusps", models.CharField(max_length=2)),
                ("name", models.CharField(max_length=100)),
                ("lsad", models.CharField(max_length=2)),
                ("mtfcc", models.CharField(max_length=5)),
                ("funcstat", models.CharField(max_length=1)),
                ("aland", models.BigIntegerField()),
                ("awater", models.BigIntegerField()),
                ("intptlat", models.CharField(max_length=11)),
                ("intptlon", models.CharField(max_length=12)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4269),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Admin_Level_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "gid_1",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "name_1",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "varname_1",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "nl_name_1",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "type_1",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "engtype_1",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "cc_1",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "hasc_1",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "iso_1",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                (
                    "gid_0",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_0",
                    ),
                ),
            ],
            options={
                "ordering": ["gid_1"],
            },
        ),
        migrations.CreateModel(
            name="Admin_Level_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "name_1",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "nl_name_1",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "gid_2",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "name_2",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "varname_2",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "nl_name_2",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "type_2",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "engtype_2",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "cc_2",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "hasc_2",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                (
                    "gid_0",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_0",
                    ),
                ),
                (
                    "gid_1",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_1",
                    ),
                ),
            ],
            options={
                "ordering": ["gid_2"],
            },
        ),
        migrations.CreateModel(
            name="Admin_Level_3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "name_1",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "nl_name_1",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "name_2",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "nl_name_2",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "gid_3",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "name_3",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "varname_3",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "nl_name_3",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "type_3",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "engtype_3",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "cc_3",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "hasc_3",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                (
                    "gid_0",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_0",
                    ),
                ),
                (
                    "gid_1",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_1",
                    ),
                ),
                (
                    "gid_2",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_2",
                    ),
                ),
            ],
            options={
                "ordering": ["gid_3"],
            },
        ),
        migrations.CreateModel(
            name="Admin_Level_4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "name_1",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "name_2",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "name_3",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "gid_4",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "name_4",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "varname_4",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "type_4",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "engtype_4",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "cc_4",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                (
                    "gid_0",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_0",
                    ),
                ),
                (
                    "gid_1",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_1",
                    ),
                ),
                (
                    "gid_2",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_2",
                    ),
                ),
                (
                    "gid_3",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_3",
                    ),
                ),
            ],
            options={
                "ordering": ["gid_4"],
            },
        ),
        migrations.CreateModel(
            name="Admin_Level_5",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "name_1",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "name_2",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "name_3",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "name_4",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "gid_5",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "name_5",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "type_5",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "engtype_5",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "cc_5",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                (
                    "gid_0",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_0",
                    ),
                ),
                (
                    "gid_1",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_1",
                    ),
                ),
                (
                    "gid_2",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_2",
                    ),
                ),
                (
                    "gid_3",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_3",
                    ),
                ),
                (
                    "gid_4",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_4",
                    ),
                ),
            ],
            options={
                "ordering": ["gid_5"],
            },
        ),
        migrations.CreateModel(
            name="Locality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("nickname", models.CharField(max_length=500)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                (
                    "gid_0",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_0",
                    ),
                ),
                (
                    "gid_1",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_1",
                    ),
                ),
                (
                    "gid_2",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_2",
                    ),
                ),
                (
                    "gid_3",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_3",
                    ),
                ),
                (
                    "gid_4",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_4",
                    ),
                ),
                (
                    "gid_5",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_5",
                    ),
                ),
                (
                    "timezone",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.timezone",
                    ),
                ),
            ],
            options={
                "verbose_name": "locality",
                "verbose_name_plural": "localities",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("nickname", models.CharField(max_length=500)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, default=None, null=True, srid=4326
                    ),
                ),
                (
                    "gid_0",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_0",
                    ),
                ),
                (
                    "gid_1",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_1",
                    ),
                ),
                (
                    "gid_2",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_2",
                    ),
                ),
                (
                    "gid_3",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_3",
                    ),
                ),
                (
                    "gid_4",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_4",
                    ),
                ),
                (
                    "gid_5",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.admin_level_5",
                    ),
                ),
                (
                    "timezone",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.timezone",
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="locations.united_states_address",
                    ),
                ),
            ],
            options={
                "verbose_name": "place",
                "verbose_name_plural": "places",
                "abstract": False,
            },
        ),
    ]
