# Generated by Django 5.2.7 on 2025-10-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin_level_1",
            name="gid_0_string",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Temp field for parallel loading",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="admin_level_2",
            name="gid_0_string",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Temp field for parallel loading",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="admin_level_2",
            name="gid_1_string",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Temp field for parallel loading",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="admin_level_3",
            name="gid_0_string",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Temp field for parallel loading",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="admin_level_3",
            name="gid_1_string",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Temp field for parallel loading",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="admin_level_3",
            name="gid_2_string",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Temp field for parallel loading",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="admin_level_4",
            name="gid_0_string",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Temp field for parallel loading",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="admin_level_4",
            name="gid_1_string",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Temp field for parallel loading",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="admin_level_4",
            name="gid_2_string",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Temp field for parallel loading",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="admin_level_4",
            name="gid_3_string",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Temp field for parallel loading",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="admin_level_5",
            name="gid_0_string",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Temp field for parallel loading",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="admin_level_5",
            name="gid_1_string",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Temp field for parallel loading",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="admin_level_5",
            name="gid_2_string",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Temp field for parallel loading",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="admin_level_5",
            name="gid_3_string",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Temp field for parallel loading",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="admin_level_5",
            name="gid_4_string",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Temp field for parallel loading",
                max_length=250,
                null=True,
            ),
        ),
    ]
