# Generated by Django 5.1.3 on 2024-11-15 19:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="US_Census_Block_Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statefp", models.CharField(max_length=2)),
                ("countyfp", models.CharField(max_length=3)),
                ("tractce", models.CharField(max_length=6)),
                ("blkgrpce", models.CharField(max_length=1)),
                ("geoid", models.CharField(max_length=12)),
                ("geoidfq", models.CharField(max_length=21)),
                ("namelsad", models.CharField(max_length=13)),
                ("mtfcc", models.CharField(max_length=5)),
                ("funcstat", models.CharField(max_length=1)),
                ("aland", models.BigIntegerField()),
                ("awater", models.BigIntegerField()),
                ("intptlat", models.CharField(max_length=11)),
                ("intptlon", models.CharField(max_length=12)),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=4269)),
                ("year", models.IntegerField(max_length=4)),
            ],
        ),
    ]
