# Generated by Django 5.0.6 on 2024-07-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_timezone_geom_alter_timezone_tzid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_level_1',
            name='cca_1',
        ),
        migrations.RemoveField(
            model_name='admin_level_1',
            name='ccn_1',
        ),
        migrations.RemoveField(
            model_name='admin_level_1',
            name='id_0',
        ),
        migrations.RemoveField(
            model_name='admin_level_1',
            name='id_1',
        ),
        migrations.RemoveField(
            model_name='admin_level_1',
            name='iso',
        ),
        migrations.RemoveField(
            model_name='admin_level_1',
            name='name_0',
        ),
        migrations.RemoveField(
            model_name='admin_level_1',
            name='shape_area',
        ),
        migrations.RemoveField(
            model_name='admin_level_1',
            name='shape_length',
        ),
        migrations.RemoveField(
            model_name='admin_level_2',
            name='cca_2',
        ),
        migrations.RemoveField(
            model_name='admin_level_2',
            name='ccn_2',
        ),
        migrations.RemoveField(
            model_name='admin_level_2',
            name='id_0',
        ),
        migrations.RemoveField(
            model_name='admin_level_2',
            name='id_1',
        ),
        migrations.RemoveField(
            model_name='admin_level_2',
            name='id_2',
        ),
        migrations.RemoveField(
            model_name='admin_level_2',
            name='iso',
        ),
        migrations.RemoveField(
            model_name='admin_level_2',
            name='name_0',
        ),
        migrations.RemoveField(
            model_name='admin_level_2',
            name='shape_area',
        ),
        migrations.RemoveField(
            model_name='admin_level_2',
            name='shape_length',
        ),
        migrations.RemoveField(
            model_name='admin_level_3',
            name='cca_3',
        ),
        migrations.RemoveField(
            model_name='admin_level_3',
            name='ccn_3',
        ),
        migrations.RemoveField(
            model_name='admin_level_3',
            name='id_0',
        ),
        migrations.RemoveField(
            model_name='admin_level_3',
            name='id_1',
        ),
        migrations.RemoveField(
            model_name='admin_level_3',
            name='id_2',
        ),
        migrations.RemoveField(
            model_name='admin_level_3',
            name='id_3',
        ),
        migrations.RemoveField(
            model_name='admin_level_3',
            name='iso',
        ),
        migrations.RemoveField(
            model_name='admin_level_3',
            name='name_0',
        ),
        migrations.RemoveField(
            model_name='admin_level_3',
            name='shape_area',
        ),
        migrations.RemoveField(
            model_name='admin_level_3',
            name='shape_length',
        ),
        migrations.RemoveField(
            model_name='admin_level_4',
            name='cca_4',
        ),
        migrations.RemoveField(
            model_name='admin_level_4',
            name='ccn_4',
        ),
        migrations.RemoveField(
            model_name='admin_level_4',
            name='id_0',
        ),
        migrations.RemoveField(
            model_name='admin_level_4',
            name='id_1',
        ),
        migrations.RemoveField(
            model_name='admin_level_4',
            name='id_2',
        ),
        migrations.RemoveField(
            model_name='admin_level_4',
            name='id_3',
        ),
        migrations.RemoveField(
            model_name='admin_level_4',
            name='id_4',
        ),
        migrations.RemoveField(
            model_name='admin_level_4',
            name='iso',
        ),
        migrations.RemoveField(
            model_name='admin_level_4',
            name='name_0',
        ),
        migrations.RemoveField(
            model_name='admin_level_4',
            name='shape_area',
        ),
        migrations.RemoveField(
            model_name='admin_level_4',
            name='shape_length',
        ),
        migrations.RemoveField(
            model_name='admin_level_5',
            name='cca_5',
        ),
        migrations.RemoveField(
            model_name='admin_level_5',
            name='ccn_5',
        ),
        migrations.RemoveField(
            model_name='admin_level_5',
            name='id_0',
        ),
        migrations.RemoveField(
            model_name='admin_level_5',
            name='id_1',
        ),
        migrations.RemoveField(
            model_name='admin_level_5',
            name='id_2',
        ),
        migrations.RemoveField(
            model_name='admin_level_5',
            name='id_3',
        ),
        migrations.RemoveField(
            model_name='admin_level_5',
            name='id_4',
        ),
        migrations.RemoveField(
            model_name='admin_level_5',
            name='id_5',
        ),
        migrations.RemoveField(
            model_name='admin_level_5',
            name='iso',
        ),
        migrations.RemoveField(
            model_name='admin_level_5',
            name='name_0',
        ),
        migrations.RemoveField(
            model_name='admin_level_5',
            name='shape_area',
        ),
        migrations.RemoveField(
            model_name='admin_level_5',
            name='shape_length',
        ),
        migrations.RemoveField(
            model_name='country',
            name='acp',
        ),
        migrations.RemoveField(
            model_name='country',
            name='agadir',
        ),
        migrations.RemoveField(
            model_name='country',
            name='aosis',
        ),
        migrations.RemoveField(
            model_name='country',
            name='asean',
        ),
        migrations.RemoveField(
            model_name='country',
            name='cacm',
        ),
        migrations.RemoveField(
            model_name='country',
            name='can',
        ),
        migrations.RemoveField(
            model_name='country',
            name='caricom',
        ),
        migrations.RemoveField(
            model_name='country',
            name='ceeac',
        ),
        migrations.RemoveField(
            model_name='country',
            name='cemac',
        ),
        migrations.RemoveField(
            model_name='country',
            name='ceplg',
        ),
        migrations.RemoveField(
            model_name='country',
            name='cis',
        ),
        migrations.RemoveField(
            model_name='country',
            name='comesa',
        ),
        migrations.RemoveField(
            model_name='country',
            name='contains',
        ),
        migrations.RemoveField(
            model_name='country',
            name='csn',
        ),
        migrations.RemoveField(
            model_name='country',
            name='developing',
        ),
        migrations.RemoveField(
            model_name='country',
            name='eac',
        ),
        migrations.RemoveField(
            model_name='country',
            name='ecowas',
        ),
        migrations.RemoveField(
            model_name='country',
            name='eu',
        ),
        migrations.RemoveField(
            model_name='country',
            name='eurasec',
        ),
        migrations.RemoveField(
            model_name='country',
            name='fips',
        ),
        migrations.RemoveField(
            model_name='country',
            name='gcc',
        ),
        migrations.RemoveField(
            model_name='country',
            name='id_0',
        ),
        migrations.RemoveField(
            model_name='country',
            name='igad',
        ),
        migrations.RemoveField(
            model_name='country',
            name='ioc',
        ),
        migrations.RemoveField(
            model_name='country',
            name='islands',
        ),
        migrations.RemoveField(
            model_name='country',
            name='iso',
        ),
        migrations.RemoveField(
            model_name='country',
            name='iso2',
        ),
        migrations.RemoveField(
            model_name='country',
            name='ison',
        ),
        migrations.RemoveField(
            model_name='country',
            name='landlocked',
        ),
        migrations.RemoveField(
            model_name='country',
            name='ldc',
        ),
        migrations.RemoveField(
            model_name='country',
            name='mru',
        ),
        migrations.RemoveField(
            model_name='country',
            name='nafta',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_english',
        ),
        migrations.RemoveField(
            model_name='country',
            name='oecd',
        ),
        migrations.RemoveField(
            model_name='country',
            name='palop',
        ),
        migrations.RemoveField(
            model_name='country',
            name='parta',
        ),
        migrations.RemoveField(
            model_name='country',
            name='pop2000',
        ),
        migrations.RemoveField(
            model_name='country',
            name='popsqkm',
        ),
        migrations.RemoveField(
            model_name='country',
            name='saarc',
        ),
        migrations.RemoveField(
            model_name='country',
            name='sacu',
        ),
        migrations.RemoveField(
            model_name='country',
            name='shape_area',
        ),
        migrations.RemoveField(
            model_name='country',
            name='shape_length',
        ),
        migrations.RemoveField(
            model_name='country',
            name='sids',
        ),
        migrations.RemoveField(
            model_name='country',
            name='sovereign',
        ),
        migrations.RemoveField(
            model_name='country',
            name='sqkm',
        ),
        migrations.RemoveField(
            model_name='country',
            name='transition',
        ),
        migrations.RemoveField(
            model_name='country',
            name='uemoa',
        ),
        migrations.RemoveField(
            model_name='country',
            name='uma',
        ),
        migrations.RemoveField(
            model_name='country',
            name='unregion1',
        ),
        migrations.RemoveField(
            model_name='country',
            name='unregion2',
        ),
        migrations.RemoveField(
            model_name='country',
            name='validfr',
        ),
        migrations.RemoveField(
            model_name='country',
            name='validto',
        ),
        migrations.RemoveField(
            model_name='country',
            name='waspartof',
        ),
        migrations.RemoveField(
            model_name='country',
            name='wbdebt',
        ),
        migrations.RemoveField(
            model_name='country',
            name='wbincome',
        ),
        migrations.RemoveField(
            model_name='country',
            name='wbother',
        ),
        migrations.RemoveField(
            model_name='country',
            name='wbregion',
        ),
        migrations.RemoveField(
            model_name='country',
            name='www',
        ),
        migrations.AddField(
            model_name='admin_level_1',
            name='cc_1',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_1',
            name='country',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_1',
            name='gid_0',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_1',
            name='gid_1',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_1',
            name='iso_1',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_2',
            name='cc_2',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_2',
            name='country',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_2',
            name='gid_0',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_2',
            name='gid_1',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_2',
            name='gid_2',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_2',
            name='nl_name_1',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_3',
            name='cc_3',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_3',
            name='country',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_3',
            name='gid_0',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_3',
            name='gid_1',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_3',
            name='gid_2',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_3',
            name='gid_3',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_3',
            name='hasc_3',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_3',
            name='nl_name_1',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_3',
            name='nl_name_2',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_4',
            name='cc_4',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_4',
            name='country',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_4',
            name='gid_0',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_4',
            name='gid_1',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_4',
            name='gid_2',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_4',
            name='gid_3',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_4',
            name='gid_4',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_5',
            name='cc_5',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_5',
            name='country',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_5',
            name='gid_0',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_5',
            name='gid_1',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_5',
            name='gid_2',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_5',
            name='gid_3',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_5',
            name='gid_4',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='admin_level_5',
            name='gid_5',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='gid_0',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_1',
            name='engtype_1',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_1',
            name='hasc_1',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_1',
            name='name_1',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_1',
            name='nl_name_1',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_1',
            name='type_1',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_1',
            name='varname_1',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_2',
            name='engtype_2',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_2',
            name='hasc_2',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_2',
            name='name_1',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_2',
            name='name_2',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_2',
            name='nl_name_2',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_2',
            name='type_2',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_2',
            name='varname_2',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_3',
            name='engtype_3',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_3',
            name='name_1',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_3',
            name='name_2',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_3',
            name='name_3',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_3',
            name='nl_name_3',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_3',
            name='type_3',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_3',
            name='varname_3',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_4',
            name='engtype_4',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_4',
            name='name_1',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_4',
            name='name_2',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_4',
            name='name_3',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_4',
            name='name_4',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_4',
            name='type_4',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_4',
            name='varname_4',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_5',
            name='engtype_5',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_5',
            name='name_1',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_5',
            name='name_2',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_5',
            name='name_3',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_5',
            name='name_4',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_5',
            name='name_5',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin_level_5',
            name='type_5',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
