# Generated by Django 5.1.3 on 2024-11-15 19:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_alter_us_census_block_group_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="United_States_Congressional_District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statefp", models.CharField(max_length=2)),
                ("cd118fp", models.CharField(max_length=2)),
                ("geoid", models.CharField(max_length=4)),
                ("geoidfq", models.CharField(max_length=13)),
                ("namelsad", models.CharField(max_length=41)),
                ("lsad", models.CharField(max_length=2)),
                ("cdsessn", models.CharField(max_length=3)),
                ("mtfcc", models.CharField(max_length=5)),
                ("funcstat", models.CharField(max_length=1)),
                ("aland", models.BigIntegerField()),
                ("awater", models.BigIntegerField()),
                ("intptlat", models.CharField(max_length=11)),
                ("intptlon", models.CharField(max_length=12)),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=4269)),
                ("year", models.IntegerField()),
            ],
        ),
    ]
