# Generated by Django 5.1.2 on 2024-10-11 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_locality_address_place_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locality",
            name="address",
        ),
        migrations.AlterField(
            model_name="place",
            name="address",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="address_set",
                to="locations.united_states_address",
            ),
        ),
    ]
