# Generated by Django 5.1.2 on 2024-10-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0005_united_states_address_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="united_states_address",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=100, default=None, max_digits=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="united_states_address",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=100, default=None, max_digits=100, null=True
            ),
        ),
    ]
