# Generated by Django 5.1.3 on 2024-11-15 19:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0005_united_states_state_legislative_district_lower"),
    ]

    operations = [
        migrations.CreateModel(
            name="United_States_State_Legislative_District_Upper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statefp", models.CharField(max_length=2)),
                ("sldust", models.CharField(max_length=3)),
                ("geoid", models.CharField(max_length=5)),
                ("geoidfq", models.CharField(max_length=14)),
                ("namelsad", models.CharField(max_length=100)),
                ("lsad", models.CharField(max_length=2)),
                ("lsy", models.CharField(max_length=4)),
                ("mtfcc", models.CharField(max_length=5)),
                ("funcstat", models.CharField(max_length=1)),
                ("aland", models.BigIntegerField()),
                ("awater", models.BigIntegerField()),
                ("intptlat", models.CharField(max_length=11)),
                ("intptlon", models.CharField(max_length=12)),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=4269)),
                ("year", models.IntegerField()),
            ],
        ),
    ]
