# Generated by Django 5.1.2 on 2024-10-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0006_alter_united_states_address_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="united_states_address",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=16, default=None, max_digits=22, null=True
            ),
        ),
        migrations.AlterField(
            model_name="united_states_address",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=16, default=None, max_digits=22, null=True
            ),
        ),
    ]
