# Generated by Django 5.0.7 on 2024-07-12 20:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0006_alter_admin_level_1_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timezone",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
