# Generated by Django 5.1.2 on 2024-10-14 01:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "locations",
            "0008_alter_admin_level_1_geom_alter_admin_level_2_geom_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="address",
        ),
        migrations.AlterField(
            model_name="locality",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name="place",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, default=None, null=True, srid=4326
            ),
        ),
    ]
