# Generated by Django 5.1.3 on 2024-11-15 20:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0009_united_states_census_county"),
    ]

    operations = [
        migrations.CreateModel(
            name="United_States_Census_State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=2)),
                ("division", models.CharField(max_length=2)),
                ("statefp", models.CharField(max_length=2)),
                ("statens", models.CharField(max_length=8)),
                ("geoid", models.CharField(max_length=2)),
                ("geoidfq", models.CharField(max_length=11)),
                ("stusps", models.CharField(max_length=2)),
                ("name", models.CharField(max_length=100)),
                ("lsad", models.CharField(max_length=2)),
                ("mtfcc", models.CharField(max_length=5)),
                ("funcstat", models.CharField(max_length=1)),
                ("aland", models.BigIntegerField()),
                ("awater", models.BigIntegerField()),
                ("intptlat", models.CharField(max_length=11)),
                ("intptlon", models.CharField(max_length=12)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4269),
                ),
                ("year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="United_States_Tribal_Tract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=2)),
                ("division", models.CharField(max_length=2)),
                ("statefp", models.CharField(max_length=2)),
                ("statens", models.CharField(max_length=8)),
                ("geoid", models.CharField(max_length=2)),
                ("geoidfq", models.CharField(max_length=11)),
                ("stusps", models.CharField(max_length=2)),
                ("name", models.CharField(max_length=100)),
                ("lsad", models.CharField(max_length=2)),
                ("mtfcc", models.CharField(max_length=5)),
                ("funcstat", models.CharField(max_length=1)),
                ("aland", models.BigIntegerField()),
                ("awater", models.BigIntegerField()),
                ("intptlat", models.CharField(max_length=11)),
                ("intptlon", models.CharField(max_length=12)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4269),
                ),
            ],
        ),
    ]
