# Generated by Django 5.1.3 on 2024-11-15 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0010_united_states_census_state_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="US_Census_Block_Group",
            new_name="United_States_Census_Block_Group",
        ),
        migrations.RenameModel(
            old_name="United_States_Congressional_District",
            new_name="United_States_Census_Congressional_District",
        ),
        migrations.RenameModel(
            old_name="United_States_State_Legislative_District_Upper",
            new_name="United_States_Census_State_Legislative_District_Lower",
        ),
        migrations.RenameModel(
            old_name="United_States_State_Legislative_District_Lower",
            new_name="United_States_Census_State_Legislative_District_Upper",
        ),
        migrations.RenameModel(
            old_name="United_States_Tribal_Tract",
            new_name="United_States_Census_Tribal_Tract",
        ),
        migrations.RenameField(
            model_name="united_states_census_state_legislative_district_lower",
            old_name="sldust",
            new_name="sldlst",
        ),
        migrations.RenameField(
            model_name="united_states_census_state_legislative_district_upper",
            old_name="sldlst",
            new_name="sldust",
        ),
    ]
