# Generated by Django 5.1.2 on 2024-10-14 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "locations",
            "0010_alter_admin_level_1_geom_alter_admin_level_2_geom_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="address",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="locations.united_states_address",
            ),
        ),
    ]
