# Generated by Django 5.1.2 on 2024-10-24 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0011_place_address"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Country",
            new_name="Admin_Level_0",
        ),
        migrations.AlterModelOptions(
            name="admin_level_0",
            options={"ordering": ["gid_0"]},
        ),
    ]
